// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAUmCeodnVrvWHeELauSf23yxgBKXqEVE',
    appId: '1:125347020717:web:a15561d08acadf26fe6b24',
    messagingSenderId: '125347020717',
    projectId: 'dating-app-e0d83',
    authDomain: 'dating-app-e0d83.firebaseapp.com',
    storageBucket: 'dating-app-e0d83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvKgnyS8ab9SrK4vxkdi1j3y2HL3MqK80',
    appId: '1:125347020717:android:bf9ef395cdecc561fe6b24',
    messagingSenderId: '125347020717',
    projectId: 'dating-app-e0d83',
    storageBucket: 'dating-app-e0d83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ-SPh2r6PX3CY4jgEC0klH_ThQ2WDgx0',
    appId: '1:125347020717:ios:9e3a8c532b3636d2fe6b24',
    messagingSenderId: '125347020717',
    projectId: 'dating-app-e0d83',
    storageBucket: 'dating-app-e0d83.firebasestorage.app',
    iosBundleId: 'com.example.kaziConnectKenya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ-SPh2r6PX3CY4jgEC0klH_ThQ2WDgx0',
    appId: '1:125347020717:ios:9e3a8c532b3636d2fe6b24',
    messagingSenderId: '125347020717',
    projectId: 'dating-app-e0d83',
    storageBucket: 'dating-app-e0d83.firebasestorage.app',
    iosBundleId: 'com.example.kaziConnectKenya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAUmCeodnVrvWHeELauSf23yxgBKXqEVE',
    appId: '1:125347020717:web:b297771391964653fe6b24',
    messagingSenderId: '125347020717',
    projectId: 'dating-app-e0d83',
    authDomain: 'dating-app-e0d83.firebaseapp.com',
    storageBucket: 'dating-app-e0d83.firebasestorage.app',
  );
}
